# Generated by Django 5.0.4 on 2024-05-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.IntegerField(max_length=100, verbose_name='Professor name'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='post',
            field=models.IntegerField(max_length=100, verbose_name='which post'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='school',
            field=models.IntegerField(max_length=100, verbose_name='which school'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='subject',
            field=models.IntegerField(max_length=100, verbose_name='subject'),
        ),
    ]
