# Generated by Django 5.0.4 on 2024-05-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_professor_name_alter_professor_post_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professor',
            new_name='Faculty',
        ),
    ]
