# Generated by Django 5.0.4 on 2024-05-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_professor_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
